Win32SDK_Gui#include	"CFControl.H"

CFControl::CFControl(int Param1) {
}

CFControl::~CFControl() {
}
//Comment : Auto Generate Set_Enabled() Function.
void	CFControl::Set_Enabled(bool _SetNewValue) {
	//ToDo : Add your Set_Enabled() Codes.
	_Enabled = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_Enabled() Function.
const	bool	CFControl::Get_Enabled() {
	//ToDo : Add your Get_Enabled() Codes.
	return	_Enabled	;
}
//Comment : Auto Generate Set_Visible() Function.
void	CFControl::Set_Visible(bool _SetNewValue) {
	//ToDo : Add your Set_Visible() Codes.
	_Visible = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_Visible() Function.
const	bool	CFControl::Get_Visible() {
	//ToDo : Add your Get_Visible() Codes.
	return	_Visible	;
}
//Comment : Auto Generate Set_Tag() Function.
void	CFControl::Set_Tag(char* _SetNewValue) {
	//ToDo : Add your Set_Tag() Codes.
	_Tag = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_Tag() Function.
const	char*	CFControl::Get_Tag() {
	//ToDo : Add your Get_Tag() Codes.
	return	_Tag	;
}
//Comment : Auto Generate Set_MousePointer() Function.
void	CFControl::Set_MousePointer(long _SetNewValue) {
	//ToDo : Add your Set_MousePointer() Codes.
	_MousePointer = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_MousePointer() Function.
const	long	CFControl::Get_MousePointer() {
	//ToDo : Add your Get_MousePointer() Codes.
	return	_MousePointer	;
}
//Comment : Auto Generate Set_IDC() Function.
void	CFControl::Set_IDC(long _SetNewValue) {
	//ToDo : Add your Set_IDC() Codes.
	_IDC = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_IDC() Function.
const	long	CFControl::Get_IDC() {
	//ToDo : Add your Get_IDC() Codes.
	return	_IDC	;
}
//Comment : Auto Generate Set_hWndSelf() Function.
void	CFControl::Set_hWndSelf(HWND _SetNewValue) {
	//ToDo : Add your Set_hWndSelf() Codes.
	_hWndSelf = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_hWndSelf() Function.
const	HWND	CFControl::Get_hWndSelf() {
	//ToDo : Add your Get_hWndSelf() Codes.
	return	_hWndSelf	;
}
//Comment : Auto Generate Set_hWndParent() Function.
void	CFControl::Set_hWndParent(HWND _SetNewValue) {
	//ToDo : Add your Set_hWndParent() Codes.
	_hWndParent = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_hWndParent() Function.
const	HWND	CFControl::Get_hWndParent() {
	//ToDo : Add your Get_hWndParent() Codes.
	return	_hWndParent	;
}
//Comment : Auto Generate Set_ToolTip() Function.
void	CFControl::Set_ToolTip(char* _SetNewValue) {
	//ToDo : Add your Set_ToolTip() Codes.
	_ToolTip = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_ToolTip() Function.
const	char*	CFControl::Get_ToolTip() {
	//ToDo : Add your Get_ToolTip() Codes.
	return	_ToolTip	;
}
//Comment : Auto Generate Set_ToolTipBalloon() Function.
void	CFControl::Set_ToolTipBalloon(bool _SetNewValue) {
	//ToDo : Add your Set_ToolTipBalloon() Codes.
	_ToolTipBalloon = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_ToolTipBalloon() Function.
const	bool	CFControl::Get_ToolTipBalloon() {
	//ToDo : Add your Get_ToolTipBalloon() Codes.
	return	_ToolTipBalloon	;
}
//Comment : Auto Generate Set_Style() Function.
void	CFControl::Set_Style(long _SetNewValue) {
	//ToDo : Add your Set_Style() Codes.
	_Style = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_Style() Function.
const	long	CFControl::Get_Style() {
	//ToDo : Add your Get_Style() Codes.
	return	_Style	;
}
//Comment : Auto Generate Set_ExStyle() Function.
void	CFControl::Set_ExStyle(long _SetNewValue) {
	//ToDo : Add your Set_ExStyle() Codes.
	_ExStyle = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_ExStyle() Function.
const	long	CFControl::Get_ExStyle() {
	//ToDo : Add your Get_ExStyle() Codes.
	return	_ExStyle	;
}
//Comment : Auto Generate Set_Align() Function.
void	CFControl::Set_Align(ControlAlign _SetNewValue) {
	//ToDo : Add your Set_Align() Codes.
	_Align = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_Align() Function.
const	ControlAlign	CFControl::Get_Align() {
	//ToDo : Add your Get_Align() Codes.
	return	_Align	;
}
//Comment : Auto Generate Set_ParentWidth() Function.
void	CFControl::Set_ParentWidth(int _SetNewValue) {
	//ToDo : Add your Set_ParentWidth() Codes.
	_ParentWidth = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_ParentWidth() Function.
const	int	CFControl::Get_ParentWidth() {
	//ToDo : Add your Get_ParentWidth() Codes.
	return	_ParentWidth	;
}
//Comment : Auto Generate Set_ParentHeight() Function.
void	CFControl::Set_ParentHeight(int _SetNewValue) {
	//ToDo : Add your Set_ParentHeight() Codes.
	_ParentHeight = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_ParentHeight() Function.
const	int	CFControl::Get_ParentHeight() {
	//ToDo : Add your Get_ParentHeight() Codes.
	return	_ParentHeight	;
}
//Comment : Auto Generate Set_AcceptFiles() Function.
void	CFControl::Set_AcceptFiles(bool _SetNewValue) {
	//ToDo : Add your Set_AcceptFiles() Codes.
	_AcceptFiles = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_AcceptFiles() Function.
const	bool	CFControl::Get_AcceptFiles() {
	//ToDo : Add your Get_AcceptFiles() Codes.
	return	_AcceptFiles	;
}
//Comment : Auto Generate Set_Parent() Function.
void	CFControl::Set_Parent(HWND _SetNewValue) {
	//ToDo : Add your Set_Parent() Codes.
	_Parent = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_Parent() Function.
const	HWND	CFControl::Get_Parent() {
	//ToDo : Add your Get_Parent() Codes.
	return	_Parent	;
}
//Comment : Auto Generate Set_Name() Function.
void	CFControl::Set_Name(char* _SetNewValue) {
	//ToDo : Add your Set_Name() Codes.
	_Name = _SetNewValue;
	return	;
}
//Comment : Auto Generate Get_Name() Function.
const	char*	CFControl::Get_Name() {
	//ToDo : Add your Get_Name() Codes.
	return	_Name	;
}
//Comment : Auto Generate SetFClassName() Function.
void	CFControl::SetFClassName(char* _SetNewValue) {
	//ToDo : Add your SetFClassName() Codes.
	FClassName = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFClassName() Function.
const	char*	CFControl::GetFClassName() {
	//ToDo : Add your GetFClassName() Codes.
	return	FClassName	;
}
//Comment : Auto Generate SetFFont() Function.
void	CFControl::SetFFont(HFONT _SetNewValue) {
	//ToDo : Add your SetFFont() Codes.
	FFont = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFFont() Function.
const	HFONT	CFControl::GetFFont() {
	//ToDo : Add your GetFFont() Codes.
	return	FFont	;
}
//Comment : Auto Generate SetFParent() Function.
void	CFControl::SetFParent(HWND _SetNewValue) {
	//ToDo : Add your SetFParent() Codes.
	FParent = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFParent() Function.
const	HWND	CFControl::GetFParent() {
	//ToDo : Add your GetFParent() Codes.
	return	FParent	;
}
//Comment : Auto Generate SetFBrush() Function.
void	CFControl::SetFBrush(HBRUSH _SetNewValue) {
	//ToDo : Add your SetFBrush() Codes.
	FBrush = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFBrush() Function.
const	HBRUSH	CFControl::GetFBrush() {
	//ToDo : Add your GetFBrush() Codes.
	return	FBrush	;
}
//Comment : Auto Generate SetFPen() Function.
void	CFControl::SetFPen(HPEN _SetNewValue) {
	//ToDo : Add your SetFPen() Codes.
	FPen = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFPen() Function.
const	HPEN	CFControl::GetFPen() {
	//ToDo : Add your GetFPen() Codes.
	return	FPen	;
}
//Comment : Auto Generate SetFCursor() Function.
void	CFControl::SetFCursor(HCURSOR _SetNewValue) {
	//ToDo : Add your SetFCursor() Codes.
	FCursor = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFCursor() Function.
const	HCURSOR	CFControl::GetFCursor() {
	//ToDo : Add your GetFCursor() Codes.
	return	FCursor	;
}
//Comment : Auto Generate SetFVisible() Function.
void	CFControl::SetFVisible(bool _SetNewValue) {
	//ToDo : Add your SetFVisible() Codes.
	FVisible = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFVisible() Function.
const	bool	CFControl::GetFVisible() {
	//ToDo : Add your GetFVisible() Codes.
	return	FVisible	;
}
//Comment : Auto Generate SetFEnabled() Function.
void	CFControl::SetFEnabled(bool _SetNewValue) {
	//ToDo : Add your SetFEnabled() Codes.
	FEnabled = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFEnabled() Function.
const	bool	CFControl::GetFEnabled() {
	//ToDo : Add your GetFEnabled() Codes.
	return	FEnabled	;
}
//Comment : Auto Generate SetFIsChild() Function.
void	CFControl::SetFIsChild(bool _SetNewValue) {
	//ToDo : Add your SetFIsChild() Codes.
	FIsChild = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFIsChild() Function.
const	bool	CFControl::GetFIsChild() {
	//ToDo : Add your GetFIsChild() Codes.
	return	FIsChild	;
}
//Comment : Auto Generate SetFBackColor() Function.
void	CFControl::SetFBackColor(COLORREF _SetNewValue) {
	//ToDo : Add your SetFBackColor() Codes.
	FBackColor = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFBackColor() Function.
const	COLORREF	CFControl::GetFBackColor() {
	//ToDo : Add your GetFBackColor() Codes.
	return	FBackColor	;
}
//Comment : Auto Generate SetFForeColor() Function.
void	CFControl::SetFForeColor(COLORREF _SetNewValue) {
	//ToDo : Add your SetFForeColor() Codes.
	FForeColor = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFForeColor() Function.
const	COLORREF	CFControl::GetFForeColor() {
	//ToDo : Add your GetFForeColor() Codes.
	return	FForeColor	;
}
//Comment : Auto Generate SetFLeft() Function.
void	CFControl::SetFLeft(int _SetNewValue) {
	//ToDo : Add your SetFLeft() Codes.
	FLeft = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFLeft() Function.
const	int	CFControl::GetFLeft() {
	//ToDo : Add your GetFLeft() Codes.
	return	FLeft	;
}
//Comment : Auto Generate SetFRight() Function.
void	CFControl::SetFRight(int _SetNewValue) {
	//ToDo : Add your SetFRight() Codes.
	FRight = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFRight() Function.
const	int	CFControl::GetFRight() {
	//ToDo : Add your GetFRight() Codes.
	return	FRight	;
}
//Comment : Auto Generate SetFTop() Function.
void	CFControl::SetFTop(int _SetNewValue) {
	//ToDo : Add your SetFTop() Codes.
	FTop = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFTop() Function.
const	int	CFControl::GetFTop() {
	//ToDo : Add your GetFTop() Codes.
	return	FTop	;
}
//Comment : Auto Generate SetFBottom() Function.
void	CFControl::SetFBottom(int _SetNewValue) {
	//ToDo : Add your SetFBottom() Codes.
	FBottom = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFBottom() Function.
const	int	CFControl::GetFBottom() {
	//ToDo : Add your GetFBottom() Codes.
	return	FBottom	;
}
//Comment : Auto Generate SetFHeight() Function.
void	CFControl::SetFHeight(int _SetNewValue) {
	//ToDo : Add your SetFHeight() Codes.
	FHeight = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFHeight() Function.
const	int	CFControl::GetFHeight() {
	//ToDo : Add your GetFHeight() Codes.
	return	FHeight	;
}
//Comment : Auto Generate SetFWidth() Function.
void	CFControl::SetFWidth(int _SetNewValue) {
	//ToDo : Add your SetFWidth() Codes.
	FWidth = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFWidth() Function.
const	int	CFControl::GetFWidth() {
	//ToDo : Add your GetFWidth() Codes.
	return	FWidth	;
}
//Comment : Auto Generate SetFBounds() Function.
void	CFControl::SetFBounds(RECT _SetNewValue) {
	//ToDo : Add your SetFBounds() Codes.
	FBounds = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFBounds() Function.
const	RECT	CFControl::GetFBounds() {
	//ToDo : Add your GetFBounds() Codes.
	return	FBounds	;
}
//Comment : Auto Generate SetFClientHeight() Function.
void	CFControl::SetFClientHeight(int _SetNewValue) {
	//ToDo : Add your SetFClientHeight() Codes.
	FClientHeight = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFClientHeight() Function.
const	int	CFControl::GetFClientHeight() {
	//ToDo : Add your GetFClientHeight() Codes.
	return	FClientHeight	;
}
//Comment : Auto Generate SetFClientWidth() Function.
void	CFControl::SetFClientWidth(int _SetNewValue) {
	//ToDo : Add your SetFClientWidth() Codes.
	FClientWidth = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFClientWidth() Function.
const	int	CFControl::GetFClientWidth() {
	//ToDo : Add your GetFClientWidth() Codes.
	return	FClientWidth	;
}
//Comment : Auto Generate SetFClientRect() Function.
void	CFControl::SetFClientRect(RECT _SetNewValue) {
	//ToDo : Add your SetFClientRect() Codes.
	FClientRect = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFClientRect() Function.
const	RECT	CFControl::GetFClientRect() {
	//ToDo : Add your GetFClientRect() Codes.
	return	FClientRect	;
}
//Comment : Auto Generate SetFAlign() Function.
void	CFControl::SetFAlign(ControlAlign _SetNewValue) {
	//ToDo : Add your SetFAlign() Codes.
	FAlign = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFAlign() Function.
const	ControlAlign	CFControl::GetFAlign() {
	//ToDo : Add your GetFAlign() Codes.
	return	FAlign	;
}
//Comment : Auto Generate SetFShowHint() Function.
void	CFControl::SetFShowHint(bool _SetNewValue) {
	//ToDo : Add your SetFShowHint() Codes.
	FShowHint = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFShowHint() Function.
const	bool	CFControl::GetFShowHint() {
	//ToDo : Add your GetFShowHint() Codes.
	return	FShowHint	;
}
//Comment : Auto Generate SetFHint() Function.
void	CFControl::SetFHint(char* _SetNewValue) {
	//ToDo : Add your SetFHint() Codes.
	FHint = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFHint() Function.
const	char*	CFControl::GetFHint() {
	//ToDo : Add your GetFHint() Codes.
	return	FHint	;
}
//Comment : Auto Generate SetFStyle() Function.
void	CFControl::SetFStyle(long _SetNewValue) {
	//ToDo : Add your SetFStyle() Codes.
	FStyle = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFStyle() Function.
const	long	CFControl::GetFStyle() {
	//ToDo : Add your GetFStyle() Codes.
	return	FStyle	;
}
//Comment : Auto Generate SetFExStyle() Function.
void	CFControl::SetFExStyle(long _SetNewValue) {
	//ToDo : Add your SetFExStyle() Codes.
	FExStyle = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFExStyle() Function.
const	long	CFControl::GetFExStyle() {
	//ToDo : Add your GetFExStyle() Codes.
	return	FExStyle	;
}
//Comment : Auto Generate SetFBorderStyle() Function.
void	CFControl::SetFBorderStyle(long _SetNewValue) {
	//ToDo : Add your SetFBorderStyle() Codes.
	FBorderStyle = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFBorderStyle() Function.
const	long	CFControl::GetFBorderStyle() {
	//ToDo : Add your GetFBorderStyle() Codes.
	return	FBorderStyle	;
}
//Comment : Auto Generate SetFStartPosition() Function.
void	CFControl::SetFStartPosition(int _SetNewValue) {
	//ToDo : Add your SetFStartPosition() Codes.
	FStartPosition = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFStartPosition() Function.
const	int	CFControl::GetFStartPosition() {
	//ToDo : Add your GetFStartPosition() Codes.
	return	FStartPosition	;
}
//Comment : Auto Generate SetFText() Function.
void	CFControl::SetFText(char* _SetNewValue) {
	//ToDo : Add your SetFText() Codes.
	FText = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFText() Function.
const	char*	CFControl::GetFText() {
	//ToDo : Add your GetFText() Codes.
	return	FText	;
}
//Comment : Auto Generate SetFTextLen() Function.
void	CFControl::SetFTextLen(long _SetNewValue) {
	//ToDo : Add your SetFTextLen() Codes.
	FTextLen = _SetNewValue;
	return	;
}
//Comment : Auto Generate GetFTextLen() Function.
const	long	CFControl::GetFTextLen() {
	//ToDo : Add your GetFTextLen() Codes.
	return	FTextLen	;
}

void	CFControl::Move(long nLeft, long nTop, long nWidth = 0, long nHeight = 0) {
	return	;
}

void	CFControl::Kill() {
	return	;
}

void	CFControl::Free() {
	return	;
}

void	CFControl::WndOrderZ(HWND hWndlnsertAfter) {
	return	;
}

void	CFControl::ReFresh() {
	return	;
}

void	CFControl::BringToFront() {
	return	;
}

void	CFControl::SendToBack() {
	return	;
}

void	CFControl::SetFocus() {
	return	;
}

void	CFControl::GetFocus() {
	return	;
}

void	CFControl::RePaint() {
	return	;
}

void	CFControl::InValidate() {
	return	;
}

void	CFControl::Update() {
	return	;
}

void	CFControl::Hide() {
	return	;
}

void	CFControl::Show() {
	return	;
}

bool	CFControl::IsFocused() {
	bool	_RetValue ;
	return	_RetValue;
}

char*	CFControl::ToString() {
	char*	_RetValue ;
	return	_RetValue;
}

void	CFControl::FlashWindow() {
	return	;
}

void	CFControl::ScrollWindow() {
	return	;
}

void	CFControl::SubclassWindow() {
	return	;
}

void	CFControl::ReDrawWindow() {
	return	;
}

void	CFControl::SetTransparent() {
	return	;
}

LRESULT	CFControl::SendMessage() {
	LRESULT	_RetValue ;
	return	_RetValue;
}
//Comment : ???????
void	CFControl::DoEvents() {
	return	;
}
//Comment : public bool Contains (System.Windows.Forms.Control ctl);
void	CFControl::Contains() {
	return	;
}
//Comment : public System.Windows.Forms.Form FindForm ();
void	CFControl::FindForm() {
	return	;
}


